### ISSUE TITLE
filesystem unit test fails to compile, cannot find `add_metadata` or `remove_metadata`

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#6219]
- [x] main
- [x] 4-2-stable
-------

When building from main, the filesystem unit test fails to compile:
```
/irods/unit_tests/src/filesystem/test_filesystem.cpp:703:29: error: no matching function for call to 'add_metadata'
            REQUIRE_NOTHROW(fs::client::add_metadata(conn, sandbox, metadata));
                            ^~~~~~~~~~~~~~~~~~~~~~~~
/opt/irods-externals/catch22.13.8-0/include/catch2/catch.hpp:17675:110: note: expanded from macro 'REQUIRE_NOTHROW'
#define REQUIRE_NOTHROW( ... ) INTERNAL_CATCH_NO_THROW( "REQUIRE_NOTHROW", Catch::ResultDisposition::Normal, __VA_ARGS__ )
                                                                                                             ^~~~~~~~~~~
/opt/irods-externals/catch22.13.8-0/include/catch2/catch.hpp:2731:31: note: expanded from macro 'INTERNAL_CATCH_NO_THROW'
            static_cast<void>(__VA_ARGS__); \
                              ^~~~~~~~~~~
/irods/lib/filesystem/include/filesystem/filesystem.hpp:265:14: note: candidate function not viable: no known conversion from 'std::array<fs::metadata, 3>' to 'const irods::experimental::filesystem::metadata' for 3rd argument
        auto add_metadata(rxComm& _comm, const path& _p, const metadata& _metadata) -> void;
             ^
/irods/lib/filesystem/include/filesystem/filesystem.hpp:279:14: note: candidate function not viable: requires 4 arguments, but 3 were provided
        auto add_metadata(admin_tag _admin, rxComm& _comm, const path& _p, const metadata& _metadata) -> void;
             ^
/irods/unit_tests/src/filesystem/test_filesystem.cpp:715:29: error: no matching function for call to 'remove_metadata'
            REQUIRE_NOTHROW(fs::client::remove_metadata(conn, sandbox, metadata));
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/irods-externals/catch22.13.8-0/include/catch2/catch.hpp:17675:110: note: expanded from macro 'REQUIRE_NOTHROW'
#define REQUIRE_NOTHROW( ... ) INTERNAL_CATCH_NO_THROW( "REQUIRE_NOTHROW", Catch::ResultDisposition::Normal, __VA_ARGS__ )
                                                                                                             ^~~~~~~~~~~
/opt/irods-externals/catch22.13.8-0/include/catch2/catch.hpp:2731:31: note: expanded from macro 'INTERNAL_CATCH_NO_THROW'
            static_cast<void>(__VA_ARGS__); \
                              ^~~~~~~~~~~
/irods/lib/filesystem/include/filesystem/filesystem.hpp:347:14: note: candidate function not viable: no known conversion from 'std::array<fs::metadata, 3>' to 'const irods::experimental::filesystem::metadata' for 3rd argument
        auto remove_metadata(rxComm& _comm, const path& _p, const metadata& _metadata) -> void;
             ^
/irods/lib/filesystem/include/filesystem/filesystem.hpp:361:14: note: candidate function not viable: requires 4 arguments, but 3 were provided
        auto remove_metadata(admin_tag _admin, rxComm& _comm, const path& _p, const metadata& _metadata) -> void;
             ^
```
I would hazard a guess that it's been broken since a8ab7ee6bfaf1e2dc84727baac49d5e81985f40b

**Comment by trel** [comment]
moving this to 4.2.12

**Comment by alanking** [comment]
Can this be checkboxed?

**Comment by korydraughn** [comment]
yes

**Comment by alanking** [comment]
Checkboxed!
